---
title: Relax Note
email: ""
author: relaxnote.com
keywords: ""
description: ''
baseurl: ''
url: ''
prod_baseurl: "http://www.relaxnote.com"
github_username: relaxnote
twitter_username: relaxnote
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 30
paginate_path: "/posts/page-:num"
permalink: /post/:slug.html
## google_analytics: ""
## baidu_analytics: "b311425eaa11ff31018da2f08edea7c3"

sass:
  sass_dir: _sass
  style: compressed

css_version: "002"
