---
title: 开发导航 - Dev800
email: ""
author: dev800.com
keywords: "w3cschool,HTML,CSS,PHP,DOM,JavaScript,jQuery,XML,AJAX,ASP.NET,W3C,MySQL,SQL,jquery mobile,bootstrap,Python,jquery easyui,jquery ui,angularjs"
description: 'dev800提供了最全的编程技术基础教程, 介绍了HTML、CSS、Javascript、Python，Java，Ruby，C，PHP , MySQL等各种编程语言的基础知识。 同时本站中也提供了大量的在线实例，通过实例，您可以更好的学习编程。'
baseurl: ''
url: ''
prod_baseurl: "http://www.dev800.com"
github_username: dev800
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 30
paginate_path: "/posts/page-:num"
permalink: /post/:slug.html
## google_analytics: ""
## baidu_analytics: "b311425eaa11ff31018da2f08edea7c3"

sass:
  sass_dir: _sass
  style: compressed

css_version: "001"
